# Site
repository: gviejo/gviejo.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Guillaume Viejo
title: Research associate
email: guillaume.viejo@mcgill.ca
website: https://gviejo.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Guillaume_Viejo
github_username:  gviejo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: guillaume-viejo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profil-min.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a research associate at the Montreal Neurological Institute  

  I am most skilled in: <mark>python</mark> and <mark>data analysis</mark>



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pynapple, a package to analyse neurophysiological data
        link: https://peyrachelab.github.io/pynapple/
        #link_text: 
        additional_links:
          - title:  PeyracheLab/pynapple
            icon: fab fa-github
            url: github.com/PeyracheLab/pynapple
          - title:  twitter/thepynapple
            icon: fab fa-twitter
            url: https://twitter.com/thepynapple
        quote: >
          Pynapple is a light-weight python library for time series analysis dedicated to neurophysiological data.
        description: 
           <font size="4"> <center> <mark>python</mark> <mark>numpy</mark>  <mark>pandas</mark>  <mark>pyqt</mark> </center> </font>
          
      - layout: top-middle
        title: Pynacollada, a collaborative repository for high level analysis in system neuroscience
        link: https://github.com/PeyracheLab/pynacollada
        #link_text:
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/PeyracheLab/pynapple
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Shared repository for high-level data analysis with the pynapple package.
        description: <font size="4"> <center> <mark>python</mark> <mark>numpy</mark>  <mark>pandas</mark>  <mark>Scikit-learn</mark> <mark>Jupyter notebook</mark> </center> </font>

  - title: Selected publications
    layout: text
    content: |
      __Precise Coupling of the Thalamic Head-Direction System to Hippocampal Ripples__  
      Viejo, Guillaume, and Adrien Peyrache. 2020.  
      *Nature Communications* 11 (1): 1–14.

      __Brain-State Invariant Thalamo-Cortical Coordination Revealed by Non-Linear Encoders__  
      Viejo, Guillaume, Thomas Cortier, and Adrien Peyrache. 2018.  
      *PLoS Computational Biology* 14 (3): e1006041.

      __Adaptive Coordination of Working-Memory and Reinforcement Learning in Non-Human Primates Performing a Trial-and-Error Problem Solving Task__  
      Viejo, Guillaume, Benoı̂t Girard, Emmanuel Procyk, and Mehdi Khamassi. 2018.  
      *Behavioural Brain Research* 355: 76–89.

      __Modeling Choice and Reaction Time During Arbitrary Visuomotor Learning Through the Coordination of Adaptive Working Memory and Reinforcement Learning__  
      Viejo, Guillaume, Mehdi Khamassi, Andrea Brovelli, and Benoı̂t Girard. 2015.  
      *Frontiers in Behavioral Neuroscience* 9: 225.
      
    

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Research associate
        link: https://www.peyrachelab.com/
        link_text: peyrachelab.com
        sub_title: Montreal Neurological Institute
        caption: January 2022 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: top-middle
        title: Postdoctoral fellow
        link: https://www.peyrachelab.com/
        link_text: peyrachelab.com
        sub_title: Montreal Neurological Institute
        caption: January 2017 - December 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: PhD Computational Neuroscience
        caption: 2013 - 2016
        sub_title: Université Pierre et Marie Curie
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my PhD, I worked 

      - layout: top-middle
        title: Master Artificial Intelligence and Decision
        caption: 2011 - 2013
        sub_title: Université Pierre et Marie Curie
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my PhD, I worked 

      - layout: top-middle
        title: Master Neuroscience
        caption: 2009 - 2011
        sub_title: Université Caen
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my PhD, I worked 
          

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
